# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x02qa\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\x12\x43reateOrderRequest\x12\x10\n\x08\x63ustomer\x18\x01 \x01(\t\"1\n\x13\x43hangeStatusRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"L\n\rOrderResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x63ustomer\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\xb8\x01\n\x0cOrderService\x12\x32\n\x08GetOrder\x12\x13.qa.GetOrderRequest\x1a\x11.qa.OrderResponse\x12\x38\n\x0b\x43reateOrder\x12\x16.qa.CreateOrderRequest\x1a\x11.qa.OrderResponse\x12:\n\x0c\x43hangeStatus\x12\x17.qa.ChangeStatusRequest\x1a\x11.qa.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETORDERREQUEST']._serialized_start=19
  _globals['_GETORDERREQUEST']._serialized_end=48
  _globals['_CREATEORDERREQUEST']._serialized_start=50
  _globals['_CREATEORDERREQUEST']._serialized_end=88
  _globals['_CHANGESTATUSREQUEST']._serialized_start=90
  _globals['_CHANGESTATUSREQUEST']._serialized_end=139
  _globals['_ORDERRESPONSE']._serialized_start=141
  _globals['_ORDERRESPONSE']._serialized_end=217
  _globals['_ORDERSERVICE']._serialized_start=220
  _globals['_ORDERSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
